name: patent-numbers
version: 0.1.0.0
#synopsis:
#description:
github: fros1y/patent-numbers
license: Apache-2.0
author: Martin Galese
maintainer: martin@patentmark.ai
copyright: Martin Gales
category: Data

ghc-options:
  - -Wall
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wmissing-deriving-strategies

dependencies:
  - base-noprelude >= 4.11 && < 10
  - relude
  - lens
  - parsec

default-extensions:
  - NoImplicitPrelude
  - DerivingVia
  - DuplicateRecordFields
  - TypeApplications
  - FlexibleContexts
  - DataKinds
  - MultiParamTypeClasses
  - TypeSynonymInstances
  - FlexibleInstances
  - NamedFieldPuns
  - RecordWildCards
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - OverloadedLabels

exposed-modules: Prelude

library:
  source-dirs: src

tests:
  patent-numbers-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - patent-numbers
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
